version: "3.8"
services:
  mongodb1:
    image: mongo

    volumes:
      - mongo-data1:/data/db
    env_file:
      - ./env/mongo.env
  deno1:
    build: ./
    ports:
      - 3001:3000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/deno.env
    depends_on:
      - mongodb1

volumes:
  mongo-data1:
