version: '3.8' 
services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db 
    env_file:
      - ./env/mongo.env
  deno:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/deno.env
    depends_on:
      - mongodb


volumes:
  mongo-data:

